/**
 * Curated `:shortcode:` → emoji map for the textarea autocomplete (GitHub-style).
 * Not exhaustive — the common set people actually reach for in PR comments,
 * commits and chat. Selecting inserts the unicode char (renders everywhere).
 */
export const EMOJI: Record<string, string> = {
  // reactions / faces
  smile: "😄",
  smiley: "😃",
  grin: "😁",
  laughing: "😆",
  joy: "😂",
  rofl: "🤣",
  sweat_smile: "😅",
  wink: "😉",
  blush: "😊",
  slightly_smiling_face: "🙂",
  upside_down_face: "🙃",
  thinking: "🤔",
  neutral_face: "😐",
  expressionless: "😑",
  no_mouth: "😶",
  smirk: "😏",
  unamused: "😒",
  roll_eyes: "🙄",
  grimacing: "😬",
  relieved: "😌",
  pensive: "😔",
  confused: "😕",
  worried: "😟",
  cry: "😢",
  sob: "😭",
  weary: "😩",
  tired_face: "😫",
  triumph: "😤",
  rage: "😡",
  angry: "😠",
  exploding_head: "🤯",
  flushed: "😳",
  scream: "😱",
  fearful: "😨",
  cold_sweat: "😰",
  sleepy: "😪",
  sleeping: "😴",
  sunglasses: "😎",
  nerd_face: "🤓",
  star_struck: "🤩",
  partying_face: "🥳",
  hugs: "🤗",
  shushing_face: "🤫",
  zipper_mouth_face: "🤐",
  raised_eyebrow: "🤨",
  monocle_face: "🧐",
  // gestures / hands
  thumbsup: "👍",
  "+1": "👍",
  thumbsdown: "👎",
  "-1": "👎",
  ok_hand: "👌",
  pinching_hand: "🤏",
  punch: "👊",
  fist: "✊",
  wave: "👋",
  raised_hands: "🙌",
  pray: "🙏",
  clap: "👏",
  handshake: "🤝",
  point_up: "☝️",
  point_down: "👇",
  point_left: "👈",
  point_right: "👉",
  muscle: "💪",
  writing_hand: "✍️",
  // hearts / symbols
  heart: "❤️",
  orange_heart: "🧡",
  yellow_heart: "💛",
  green_heart: "💚",
  blue_heart: "💙",
  purple_heart: "💜",
  black_heart: "🖤",
  broken_heart: "💔",
  sparkling_heart: "💖",
  hundred: "💯",
  exclamation: "❗",
  question: "❓",
  warning: "⚠️",
  white_check_mark: "✅",
  heavy_check_mark: "✔️",
  x: "❌",
  no_entry: "⛔",
  no_entry_sign: "🚫",
  recycle: "♻️",
  // dev / work
  rocket: "🚀",
  fire: "🔥",
  tada: "🎉",
  sparkles: "✨",
  boom: "💥",
  zap: "⚡",
  bug: "🐛",
  beetle: "🪲",
  ant: "🐜",
  wrench: "🔧",
  hammer: "🔨",
  hammer_and_wrench: "🛠️",
  gear: "⚙️",
  nut_and_bolt: "🔩",
  lock: "🔒",
  unlock: "🔓",
  key: "🔑",
  mag: "🔍",
  bulb: "💡",
  memo: "📝",
  pencil: "✏️",
  pushpin: "📌",
  paperclip: "📎",
  link: "🔗",
  package: "📦",
  label: "🏷️",
  bookmark: "🔖",
  clipboard: "📋",
  calendar: "📅",
  hourglass: "⏳",
  alarm_clock: "⏰",
  stopwatch: "⏱️",
  chart_with_upwards_trend: "📈",
  chart_with_downwards_trend: "📉",
  bar_chart: "📊",
  computer: "💻",
  keyboard: "⌨️",
  floppy_disk: "💾",
  satellite: "📡",
  battery: "🔋",
  electric_plug: "🔌",
  test_tube: "🧪",
  microscope: "🔬",
  telescope: "🔭",
  dna: "🧬",
  brain: "🧠",
  robot: "🤖",
  alien: "👽",
  ghost: "👻",
  skull: "💀",
  poop: "💩",
  // status / signals
  green_circle: "🟢",
  red_circle: "🔴",
  yellow_circle: "🟡",
  large_blue_circle: "🔵",
  white_circle: "⚪",
  black_circle: "⚫",
  star: "⭐",
  star2: "🌟",
  dizzy: "💫",
  zzz: "💤",
  speech_balloon: "💬",
  thought_balloon: "💭",
  eyes: "👀",
  // misc objects
  coffee: "☕",
  beer: "🍺",
  pizza: "🍕",
  hamburger: "🍔",
  cookie: "🍪",
  cake: "🍰",
  gift: "🎁",
  balloon: "🎈",
  trophy: "🏆",
  medal: "🏅",
  dart: "🎯",
  game_die: "🎲",
  crystal_ball: "🔮",
  hot: "🥵",
  cold: "🥶",
  snowflake: "❄️",
  sunny: "☀️",
  cloud: "☁️",
  rainbow: "🌈",
  ocean: "🌊",
  earth_americas: "🌎",
  seedling: "🌱",
  herb: "🌿",
  four_leaf_clover: "🍀",
  cat: "🐱",
  dog: "🐶",
  unicorn: "🦄",
  whale: "🐳",
  turtle: "🐢",
  snail: "🐌",
  butterfly: "🦋",
  honeybee: "🐝",
};

export interface EmojiMatch {
  shortcode: string;
  char: string;
}

/**
 * Rank emoji by a `:` query: exact first, then prefix, then substring.
 * Empty query returns a small "popular" default set.
 */
export function searchEmoji(query: string, limit = 8): EmojiMatch[] {
  const q = query.toLowerCase();
  if (!q) {
    return ["+1", "tada", "rocket", "heart", "eyes", "fire", "sparkles", "white_check_mark"]
      .filter((s) => EMOJI[s])
      .slice(0, limit)
      .map((s) => ({ shortcode: s, char: EMOJI[s] }));
  }
  const exact: EmojiMatch[] = [];
  const prefix: EmojiMatch[] = [];
  const sub: EmojiMatch[] = [];
  for (const [shortcode, char] of Object.entries(EMOJI)) {
    if (shortcode === q) exact.push({ shortcode, char });
    else if (shortcode.startsWith(q)) prefix.push({ shortcode, char });
    else if (shortcode.includes(q)) sub.push({ shortcode, char });
  }
  return [...exact, ...prefix, ...sub].slice(0, limit);
}
